28 current  2024-12-09 11:16:20  24.11.710650.e2605d0744c2  6.6.63                          *

diff --git a/.config/nixos/rebuild b/.config/nixos/rebuild
--- a/.config/nixos/rebuild
+++ b/.config/nixos/rebuild
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+# Check if ~/.bashrc exists and source it, or panic if it's missing
+if [ ! -f "$HOME/.bashrc" ]; then
+  echo "Error: ~/.bashrc not found!"
+  exit 1 # Exit with a non-zero status to indicate failure
+else
+  source "$HOME/.bashrc"
+fi
+
 # A rebuild script that commits on a successful build
 set -e
 
