27 current  2025-05-26 11:38:22  25.05.802491.7c43f080a7f2  6.12.30                          *

diff --git a/scripts/.scripts/nixos/rebuild b/scripts/.scripts/nixos/rebuild
--- a/scripts/.scripts/nixos/rebuild
+++ b/scripts/.scripts/nixos/rebuild
@@ -35,11 +35,8 @@ if dotfiles diff --quiet "$CONFIG_DIR/*.nix"; then
 fi
 
 # Autoformat your nix files
-alejandra . &>/dev/null ||
-    (
-        alejandra .
-        echo "formatting failed!" && exit 1
-    )
+alejandra --experimental-config "$HOME/.alejandra.toml" . &>/dev/null ||
+    (alejandra --experimental-config "$HOME/.alejandra.toml" . && echo "formatting failed!" && exit 1)
 
 # Shows your changes
 dotfiles diff -U0 "$CONFIG_DIR/*.nix"
